import type { ScanResult } from '@/lib/schemas';

export function buildReportMarkdown(result: ScanResult): string {
  const lines: string[] = [];
  lines.push(`# Codex-Readiness Report`);
  lines.push('');
  lines.push(`**Language:** ${result.language}`);
  lines.push(`**Codex-Readiness Score:** ${result.codebaseReadinessScore}/100`);
  lines.push('');
  lines.push(result.summary);
  lines.push('');
  lines.push(`## Candidates (${result.candidates.length})`);
  lines.push('');

  result.candidates.forEach((c, i) => {
    lines.push(`### ${i + 1}. ${c.title}`);
    lines.push('');
    lines.push(
      `- **Category:** ${c.category}  ·  **Codex fit:** ${c.codexFitScore}/100  ·  **Est. saved:** ~${c.estimatedMinutesSaved} min  ·  **Confidence:** ${c.confidence}`,
    );
    if (c.filePath) lines.push(`- **File:** ${c.filePath}${c.startLine ? `:${c.startLine}` : ''}`);
    lines.push('');
    lines.push(c.reason);
    lines.push('');
  });

  const total = result.candidates.reduce((s, c) => s + c.estimatedMinutesSaved, 0);
  lines.push(`## Total estimated one-time savings`);
  lines.push('');
  lines.push(`~${total} minutes (~${Math.round((total / 60) * 10) / 10} hours)`);
  lines.push('');
  lines.push(`---`);
  lines.push(`Generated by Codex Usage Analyzer.`);

  return lines.join('\n');
}

export function downloadMarkdown(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
